name: GetUserData

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get Users List
        run: ./gradlew test

      - name: Push Users List
        run: |
          git config --global user.email "a.urusihara@gmail.com"
          git config --global user.name "Akihiro Urushihara"
          git add --all
          git commit -m "Refreshed by GitHub Actions CI (SHA ${GITHUB_SHA})"
          git remote add origin https://${GH_TOKEN}@github.com/uakihir0/mildom-user-list.git
          git push -f origin master